### ISSUE TITLE
Wrangle/sweep priority setting

### ISSUE THREAD

**Issue by kaedys** [Truinto/ONI-Modloader-SimpleMods#10]
**Is your feature request related to a problem? Please describe.**

So, one thing that has somewhat annoyed me is that the sweep and wrangle jobs are always assigned at priority 5.  In order for the sweeps, and especially the _wrangles_, to actually happen, I either have to manually adjust the priority or wait for my ranchers to finish their higher priority jobs.  If wrangling in a location is particularly important (ie. needs to be the highest priority for ranchers), this really only leaves me able to assign priorities 1-4 for other ranching stuff (and requires ranching to be at least one arrow up from any other task type for my ranchers).

**Describe the solution you'd like**

The easiest solution I've come up with is being able to set a priority on the building itself, once built, and then that priority is used for all sweep and wrangle commands that building issues.

**Describe alternatives you've considered**

I could also see a secondary UI tab off the building window where you can set it, but I feel like that might be reinventing the wheel, unless querying for a building's priority is difficult or a building can't "have" a priority unless it also has something dupes can do with it.

**Comment by Truinto** [comment]
Implemented as described. Sweeping priority is copied from building.
