### ISSUE TITLE
Option to plan buildings without materials

### ISSUE THREAD

**Issue by ohcibi** [Truinto/ONI-Modloader-SimpleMods#12]
**Is your feature request related to a problem? Please describe.**
This mod is super awesome as it combines a bunch of different mods into one, reducing the area for incompatibilities and base-game-update issues a lot. One thing that should be default in game and what I would call a 'bug' (of the base game to be clear) is the missing ability to put blueprints when there is not enough of the desired material. Since the games mechanic to count the material is unreliable this leads to a lot of situations where you cannot build something while the required material is laying right in front of one dupe.

**Describe the solution you'd like**
Long story short: Would love if this mod to include the 'plan building without material' feature as an additional (tuning?) setting. If turned on player should be able to select all possible material and place blueprints accordingly.

**Describe alternatives you've considered**
 Alternatives or even additions/fine tuning might be
* make sure the material does not switch automatically**
* Make the game not not exclude material that has been 'planned' to be used for some building for calculating the total amount of that material. In other words: only subtract material when it is actually used up (added to a construction or inserted into a buildings storage). As long as the material is laying around or put into storages it should be considered "available".

**additional context**
**  When building a lot of stuff at once, the vanilla game changes the selected material silently when a) the initially selected one is empty AND b) there is enough of another material available. So for example you want to build a bunch of ceramic pipes but don't have enough ceramic yet. If you do it to fast without looking at the material you end up planning them with some random other material.

**Comment by Truinto** [comment]
MaterialIgnoreInsufficientMaterial
MaterialAutoSelect

Building without material is already a mod. I still added it, since it's such a easy function. I also added a flag for material auto selection, which should stop material being selected (due to low storage). Please test these settings.
