### ISSUE TITLE
[Customize Buildings] Crash with Skill Station

### ISSUE THREAD

**Issue by andr9528** [Truinto/ONI-Modloader-SimpleMods#14]
**Describe the bug**
Crash when using 'Skill Station' and having the Dupe undergoing the procedure selected. Unknown if only occurs when doing Attribute increase, or if the other functions of the Skill station also behaves similarly.

**To Reproduce**
1. Enable Skill Station in settings.
2. Open a World.
3. Build a Skrill Scrubber.
4. Assign a Dube with sufficient experience for procedures.
5. Select any Attribute to increase.
6. Select the dupe undergoing procedure.
7. Watch Procedure.
8. Crash.

**Debug Logs**
- attach log found here: %AppData%\..\Klei\Oxygen Not Included
  - [Player-prev.log](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/6986997/Player-prev.log)
  - [Player.log](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/6986998/Player.log)

- attach log(s) found here: Steam\SteamApps\common\OxygenNotIncluded\Mods\_Logs
  - FileNotFoundException. Jokes aside, i do not have any (Mods) folder at the specified location. hope the other logs are sufficient.

The thrown exception, as displayed by the game:

> NullReferenceException: Object reference not set to an instance of an object
> 
> MinionTodoSideScreen.PopulateElements (System.Object data) (at <4d5210689d454b148ee8bf399a4b6b43>:0)
> Scheduler.Update () (at <4d5210689d454b148ee8bf399a4b6b43>:0)
> UIScheduler.Update () (at <4d5210689d454b148ee8bf399a4b6b43>:0)
>
> Build: U33-474321-S

**Desktop:**
 - OS: Windows 10
 - Version U33-474321-S (ONI version right?; With DLC1)

**Additional context**
Wanted to watch the number increase on the dupe as it finished the procedure, but crashed instead. Accidentally found out the number doesn't update until world reloads or perhaps the attribute naturally increases.
Works fine if anything else other than the dupe undergoing the procedure is seleccted.

Fell free to ask, if there is anything else i can supply you with.

**Comment by andr9528** [comment]
Scrath the whole stats not visually updating. Number updated correctly this time for me.

**Comment by StrikerMack** [comment]
This happened to me as well. Deselect the duplicant when doing this and the game won't crash. If the dupe is selected then when procedure completes the game will crash.

**Comment by Truinto** [comment]
Well, I obviously didn't test it with the dupe selected. Will look into it.

**Comment by Truinto** [comment]
Fixed by only updating the sidescreen, when the widget for the reset station is actually selected.
