### ISSUE TITLE
[Customize Buildings] Skill Station Improvements

### ISSUE THREAD

**Issue by andr9528** [Truinto/ONI-Modloader-SimpleMods#15]
**Is your feature request related to a problem? Please describe.**
Wanting to spend 5, 6 ,7+ skillpoints worth of experience on attributes i quite repetitive

**Describe the solution you'd like**
It would be cool if we could set an amout of times to repeat the selected choice, or simply set how many to increase it by, and the time in the machine/experience cost is then simply multiplied by the requested amount.

**Describe alternatives you've considered**
Also tried to have multiple skill scrubbers, but it turns out you can only assign a dube to one at a time, so that didn't work.

**Additional context**
Would heaily improve the usefullness of the skill station, as i currently have learned just about all aptitudes on my current 8 dupes, along with almost all positive non-skill traits. I am halfway throught my dupes, (who had around 9 skillpoints) and i have been working on it for a little over an hour...

**Comment by Truinto** [comment]
The option has a value to set the time. You can pick 1 second, which mostly leaves you with the animation time of getting in/out of the pod.

Other than that, I guess it would be possible to have a slider that multiplies the attribute gain. There are already 2 sidescreens, so I think it would probably cut off the other screens... The easiest solution would be to have an option that just changes the +1 attribute to +x attribute. But that means changing the value x requires a restart.

**Comment by andr9528** [comment]
It is only slightly annoying the time that each procedure takes. It is more the amount of clicks it take to use up all the experience. Reducing the time each procedure takes, doesn't reduce the amount of clicks needed, which is where most of the annoyance comes from, especially if it is the same attribute that you wish to increase by alot.

Each skillpoint takes around 3 attribute increases to consume, Each procedure takes 2 clicks, one to select dube and one to select procedure. You also have to select the skill scrubber atleast ones, maybe more times if you are doing other things at the same time.

Lets try and calculate the minimum clicks needed to consume 5 skillpoints.
 1 * Skill Scrubber Selections + (2 * (3 * Skill Point to spend)) --> 1 * 1 + (2 * (3 * 5)) --> 1 + (2 * 15) --> 1 + 30 = 31

That was only with 5 skillspoint, and the player never deselecting the Skill Scrubber. Each extra skillpoint requires another 6 clicks to consume.

Perhaps what is needed is an entirely new building, with its own UI, however that might be done. I havn't gotten started on doing ONI modding yet, but i am planning to within the next week or two. Could start out trying to construct a better UI, for complex things like this. Come to think of it. I can use it for one of my own ideas too. Need to look into the limitation that ONI has.

**Comment by andr9528** [comment]
Oh and didn't even take into consideration for the calculation that you might have many dupes who need to spend their experience, so the "30" has to be multiplied by the amount of dupes that is gonna spend 5 skill points. It adds up to alot of clicks in the end.

**Comment by Swoop376** [comment]
my god im so sorry i just saw the answer !!!

**Comment by Truinto** [comment]
The station does now re-queue the job, if the dupe has enough exp. This might be undesirable for other players, but I leave it until I have a better idea.

> Perhaps what is needed is an entirely new building

I can see no benefit from this. Harmony grants full control over the code.

> with its own UI

Unity is build to be used with their editor. It is incredible painful to create UI elements from scratch. It like speedrunning a game while being blindfolded. Just assume it's not possible and think of clever way to recycle existing UIs.
