### ISSUE TITLE
[Linux] [Customize Buildings] Crashes ONI silently on startup

### ISSUE THREAD

**Issue by Jemsterr** [Truinto/ONI-Modloader-SimpleMods#17]
**Describe the bug**

**To Reproduce**
1. Subscribe to Customize Bulidings
2. Activate Customize Bulidings
3. Load ONI on Linux
4. Look at your destop as ONI silently disappears. [Edit: Klei logo appears, then crash]

**[required] Debug Logs**
- attach log found here: %AppData%\..\LocalLow\Klei\Oxygen Not Included
[Player-prev.log](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/7072312/Player-prev.log)

- attach log(s) found here: Steam\SteamApps\common\OxygenNotIncluded\Mods\_Logs
~/.steam/steamapps/common/OxygenNotIncluded has no Mods folder
~/.config/unity3d/Klei/Oxygen Not Included/mods has no _Logs folder

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3

**Additional context**
This is the same error that I encountered in Fixed Ore Scrubber
https://github.com/PsychoDad9999/ONI-Mods/issues/1

I don't know what he did to fix it, but linked here for what it's worth.

**Comment by Jemsterr** [comment]
Also see
https://github.com/Truinto/Nightinggale-ONI-mods/issues/1
I just realised that that was your repo, too.  Seems to be the same problem.

**Comment by Truinto** [comment]
Okay. That means that one (or more) of the hundreds patch signatures is illegal. Assuming that Klei changed a building, this could be any patch in the entire mod... The log file doesn't tell which and I have no way of testing it myself. Setting up a Linux machine isn't really an option for me.

I can only dig through every patch and check for that condition. That will take hours.

Maybe you can help me narrow the issue. Use this config file [CustomizeBuildings.zip](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/7109410/CustomizeBuildings.zip) and try booting. If it works, enable options until it crashes. Most options have either a 'global'-flag or a enabled when they are not the default value (just at +1 to numbers).

**Comment by Jemsterr** [comment]
Thanks.  I'll start the debug tonight after the wife and kids are in bed.

**Comment by Jemsterr** [comment]
Ran a diff between the two config files.
Only adjusting the settings that had been changed between the .json that is shipped with the mod and the one you provided.  The only setting that crashed the game was:
"LadderCometInvincibility": true,

But I did not make these changes:
![image](https://user-images.githubusercontent.com/17609227/132090906-69ed579f-9c89-47ac-89f5-c2e53a969e2c.png)

**Comment by Truinto** [comment]
Ugh, this feature again. For some reason that's already the 3rd time this one patch makes problems. Thanks a lot for the help. The fix took only a few minutes :)
