### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Ventulus-lab** [Truinto/ONI-Modloader-SimpleMods#19]
hello,I have made the chinese translated .po file of customize geyser.Can you add it to your mod please?
I  don't know how to test it
[strings_zh.zip](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/7084956/strings_zh.zip)
oh,sorry,corrected it

**Comment by Truinto** [comment]
I would like to. It seems you mixed up the files. The content of that zip is solely from PeterHan.

**Comment by Ventulus-lab** [comment]
oh,sorry,corrected it
https://github.com/Truinto/ONI-Modloader-SimpleMods/files/7084956/strings_zh.zip

**Comment by Truinto** [comment]
Cool, thanks a lot. I published it.
