### ISSUE TITLE
Translation for Customize Buildings

### ISSUE THREAD

**Issue by Ventulus-lab** [Truinto/ONI-Modloader-SimpleMods#24]
hi  Truinto 
I made the Chinese .po file for your mod Customize Buildings.
I hope this mod will be used by more players.
I dont know how to test it
[zh.zip](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/7828351/zh.zip)

**Comment by Truinto** [comment]
Super cool. Will check it out as soon as I can (tomorrow).

**Comment by Truinto** [comment]
I uploaded the translation. I trust it's genuine, since I don't speak the language.

About testing the languages, just rename the file as 'strings_zh.pot'
At the time I code it, I wasn't aware that the output format of the Poedit software is 'zh.po'
Small nuance, your settings will get lost when changing language. I hope to fix that someday.

Thanks for your contribution.

**Comment by Ventulus-lab** [comment]
@Truinto 
Oh, 'strings_zh.pot' seems dont work.
As in your another mod  CustomizeGeyser,“strings_zh_klei.pot” maybe the right name.
In fact,in Klei's offical game file,it's zh_klei.po file.
In most mods,including Plib,it's zh.po

**Comment by Ventulus-lab** [comment]
So I update the file with "PowerTransformerLarge"..ver 1.0.51.0
here the right  file
[strings_zh_klei.zip](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/7834528/strings_zh_klei.zip)

**Comment by Ventulus-lab** [comment]
By the way, I don't quite understand exactly which options "BuildingAdvancedGlobalFlag" and "BuildingBaseSettingGlobalFlag" are used for. I hope that the option descriptions are clearer

**Comment by Truinto** [comment]
I forgot about the _klei part. I changed the code so it's less confusion (3rd party translations are simply 2 letters). It will now just search for "strings_xx.pot", regardless if it's from Klei or not.

I could not use 'zh.po'. For whatever reason, when I have any file with the extension '.po' it will crash the game when opening the language screen. I bet there is a requirement or file structure I violate.

Thanks for the updated language file. I will try the reset button.

All "GlobalFlag" settings simple toggle their respective category completely off. Like BuildingAdvancedGlobalFlag on false will make the mod not load any of the advanced options (BuildingAdvancedMachineMultiplier, BuildingAdvancedMaterial, BuildingAdvancedOutputTemp, AdvancedSettings). This allows for quicker disabling of these features without losing the tables and (more importantly) if there is a big update or incompatibility it should make it so the mod is at least partially usable without crashing.

**Comment by Ventulus-lab** [comment]
@Truinto 
sorry the file above was made before i can test it(1.0.55).now i think that some strings can be translated more accturately.i will make it tomorrow. So you don't have to rush to upload it to Steam

**Comment by Truinto** [comment]
Ups, too late. Thought you were done. I did try out the Klei reset function no problem. I think there is a bad combination of buttons, which will make it forget the settings. I did not figure out when or why that happens. As long as you press the "restart now" button after changing the settings, you should be fine.
