### ISSUE TITLE
TUNING.ROCKETRY.OXIDIZER_EFFICIENCY

### ISSUE THREAD

**Issue by Ventulus-lab** [Truinto/ONI-Modloader-SimpleMods#28]
In your mod ,CustomizeBuildingsState.StateManager.State.TuningOxidizerEfficiencyVeryLow;Low;High; are default 1;2;4,
Set to game value ROCKETRY.OXIDIZER_EFFICIENCY.VERY_LOW;LOW;HIGH.
But In fact,there are 2 class in game 
```
                // Token: 0x0200194E RID: 6478
		public class OXIDIZER_EFFICIENCY
		{
			// Token: 0x0400726B RID: 29291
			public static float VERY_LOW = 0.334f;

			// Token: 0x0400726C RID: 29292
			public static float LOW = 1f;

			// Token: 0x0400726D RID: 29293
			public static float HIGH = 1.33f;
		}

		// Token: 0x0200194F RID: 6479
		public class DLC1_OXIDIZER_EFFICIENCY
		{
			// Token: 0x0400726E RID: 29294
			public static float VERY_LOW = 1f;

			// Token: 0x0400726F RID: 29295
			public static float LOW = 2f;

			// Token: 0x04007270 RID: 29296
			public static float HIGH = 4f;
		}
```
maybe you should set to  DLC1_OXIDIZER_EFFICIENCY

**Comment by Ventulus-lab** [comment]
And about EnginePower
I think Carbon Dioxide Engine is EARLY_STRONG = 23;
Sugar Engine is EARLY_WEAK = 16;
Steam Engine is  MID_WEAK = 27;
Small Petroleum Engine is MID_STRONG = 31;
Petroleum Engine is  MID_VERY_STRONG = 48;
Radbolt Engines is LATE_STRONG = 34;
Hydrogen Engine is LATE_VERY_STRONG = 55;

**Comment by Ventulus-lab** [comment]
And about FUEL_COST_PER_DISTANCE
I think it's 600* value;
Carbon Dioxide Engine is GAS_LOW = 0.027777778;In game 16.7;
Sugar Engine is separately in class SugarEngineConfig FUEL_EFFICIENCY = 0.125f;In game 75;
Steam Engine is GAS_VERY_LOW = 0.025f;In game 15;
Small Petroleum Engine is MEDIUM = 0.075f;In game 45;
Petroleum Engine is VERY_HIGH = 0.15f;In game 90;
Radbolt Engines is PARTICLES = 0.33333334f;In game 200;
Hydrogen Engine is HIGH = 0.09375f;In game 56.3;

**Comment by Truinto** [comment]
Is fixed and I will update with the other patches.
