### ISSUE TITLE
Update CustomizeGeyser translation file

### ISSUE THREAD

**Issue by Truinto** [Truinto/ONI-Modloader-SimpleMods#29]
[strings_customize geyser.zip](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/7900132/strings_customize.geyser.zip)

This file includes upcoming strings from [1.0.16.0]

**Comment by Truinto** [comment]
Mh... I missed the key "geyser_molten_steel"

**Comment by Ventulus-lab** [comment]
well ,what do RandomizerHighlanderMode and RandomizerHighlanderRetroactive and Randomizer Rerolls Cycle Rate mean?

**Comment by Truinto** [comment]
'Highlander' mode broke after a game update. I didn't manage to fix the issue. ~~Maybe I should remove the texts until then...~~ I just noticed I already removed them from the ingame menu. It's just the PROPERTY that's left over. There is no need to translate them (until I fix the feature).

To the meaning; Highlander is an old movie about a group of immortals. They can only be killed by each other and when they do they get all the strength of the other. The catch phrase is "There can only be one".
The idea is that only one of each geyser types can spawn.

RandomizerHighlanderMode - game rule where only one of each geysers can spawn (prefix 'Randomizer' underlines that this only works while the randomizer patch is enabled)

RandomizerHighlanderRetroactive - geysers will change type retroactively; meaning even already visible geysers will change to fulfill the rule

RandomizerRerollsCycleRate - whenever or not the geysers properties (like eruption/dormancy/kg per cycle) are defined by the map seed; 'true' will re-roll all properties ignoring the map seed

By the way, the mod already has an incomplete string_zh file! You might be aware, but I should have pointed this out.

**Comment by Ventulus-lab** [comment]
Klei add some geysers in Spaced Out DLC   official game
https://oxygennotincluded.fandom.com/wiki/Geyser

**Comment by Ventulus-lab** [comment]
[strings_zh.zip](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/7918973/strings_zh.zip)
done

**Comment by Truinto** [comment]
During play testing I found another missing string. Sorry 😅 
Would you translate this sentence:
"Click for next geyser type."

I will manually add it to the pot files.

**Comment by Ventulus-lab** [comment]
"点击切换下一种间歇泉。"

**Comment by Truinto** [comment]
👍 published
