### ISSUE TITLE
Slider Gas/Liquid Reservoir, Storage

### ISSUE THREAD

**Issue by WardenCommander** [Truinto/ONI-Modloader-SimpleMods#3]
Can you make that have slider to adjust storage capacity

also could you make that Reservoirs could be made from all materials?
or at least from isolation, and heat conductive material...

then you could use Reservoirs as cold/hot gas/liquid storage, or heat/cool down liquid/gas in Reservoirs

**Comment by Truinto** [comment]
It's already possible to change the build material of any building. I admit it's not intuitive, but I don't see how it could be done differently with the tools we have.
Note that the stored liquid/gas is a separate entity from the reservoir itself. As far as I observed, it doesn't actually insulate the storage when build from insulating material and same with conductive material. I can fix the insulation issue, but making it more conductive isn't something I know about.
Further, when you have a big concentration of material, like 100 tons of water, it will naturally be very resistant to heat changes. There is already an ingame solution with the aqua tuner.

End note, will not work on this for now. Too much other stuff.
