### ISSUE TITLE
update 3 mods Chinese translation

### ISSUE THREAD

**Issue by Ventulus-lab** [Truinto/ONI-Modloader-SimpleMods#30]
[zh.zip](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/7923925/zh.zip)
oah,here are 3 .po file
CustomizeBuildings 
-update RocketHeight strings
CustomizeGeyser
-update some geyser parameters translation after testing
CarePackageMod
-New Chinese translation
 For this mod, is there a switch to select whether or not it affects the content in CarePackages? As I have another mod that adds items to CarePackages, I don't know if the two mods will conflict or overwrite.
And then for the "always3Interests" option, could you add the "2" and "1" options? Some players may feel that 2-interests dupe would be better.
For the "allowOnlyDiscoveredElements" option, I would like to ask if it is "true" by default in the game or not?

**Comment by Truinto** [comment]
[CarePackageMod.zip](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/7945409/CarePackageMod.zip)

Thanks. I added these changes to carepackage mod which allows any range to be set (up to 3):
## [1.0.14.0] U39-490405-S
- replaced always3Interests with min and max number of interests
- added option to not load packages (for players that only want to change interests)

Obviously it has a couple new strings 😅 
I will upload the patches once I have bugfixed everything. Hope to finish tomorrow.

**Comment by Ventulus-lab** [comment]
here the file 
[CarePackageMod_zh.zip](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/7947986/CarePackageMod_zh.zip)
 I learned that some of the the carepackage will appear as soon as the cycle is up, while others have a double limit of "cycle + discovery". If I don't tick the "allowOnlyDiscoveredElements" option, it won't affect the game's default settings?

**Comment by Truinto** [comment]
Updated.

Not sure what you mean. There are probably slight changes to packages (unless you turn them off completely). Most of them are inconsequential. For example Klei's package "Water" will not check if it was discovered. With my mod and allowOnlyDiscoveredElements any package will check for discovery, even Water. However every colony must have water discovered, so it's pretty much identical.

Thanks again for your help with translation.
