### ISSUE TITLE
mod feature request

### ISSUE THREAD

**Issue by Ventulus-lab** [Truinto/ONI-Modloader-SimpleMods#32]
I have an idea and request u to add a feature to your mod Customize Buildings.
That is improving the Compost, which not only fills in Rot Pile or Polluted Dirt, but also has a freshness slider. Food below the freshness setting can also be automatically put into the Compost for composting.
It occurs to most players in the mid to late game automatically producing excess food.The food preservation mechanic in turn dictates that unless it is specially preserved, the freshness of many foods will drop below 50% until they spoil.It's too much of a hassle to hand select click compost for food that isn't fresh.

**Comment by Ventulus-lab** [comment]
. I know what happens to food when it rots under normal circumstances. I just really dislike food that is less than 50% fresh. 
I would like them to be disposed of as soon as possible. Instead of waiting for rotting  or needing to be clicked on manually.

**Comment by Ventulus-lab** [comment]
You were fantastic! I will test it as soon as I can.

**Comment by Truinto** [comment]
After installation, you need to set the freshness setting anything but zero, then reboot. The slider on the composter is global. It will search for food about every 30 in game seconds.

**Comment by Ventulus-lab** [comment]
[zh.zip](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/8050964/zh.zip)
I have finished the new strings.
By the way ,the Geysers' official Chinese names were changed due to my advice. So I update CustomizeGeyser_zh.po with the new geyser names.

**Comment by Truinto** [comment]
updated both mods
