### ISSUE TITLE
Partitioned Storage Functionality toggle

### ISSUE THREAD

**Issue by TheFantasticLoki** [Truinto/ONI-Modloader-SimpleMods#36]
**Is your feature request related to a problem? Please describe.**
I Hate not being able to specify specific amounts of items to be stored in certain storage containers. Partitioned Storage does what I am looking for except it doesn't cover conveyor receptacles and therefore also logistic receptacles from dupe logistics. It also does not support send/recieve nodes for teleport conduits which means I can't specify specific amounts of resources for specific channels causing the channels to get clogged when something fills up like a receptacle for ores, since the main storage out node is full of 1 ore it can't send any other resources that need to be sorted. 

**Describe the solution you'd like**
I'd like to see the ability to add this filter functionality from Partitioned Storage to other buildings like the receptacles at the very least.
**Describe alternatives you've considered**
I've tried many in game alternatives but the whole point of the system is to reduce conveyor clutter etc from the map so adding more to circumvent this issue makes less sense.

**Additional context**

**Comment by TheFantasticLoki** [comment]
Or at the very least add functionality to the conveyor loader so we can use it as a sorting distribution system.

**Comment by Truinto** [comment]
I think that's something for Partitioned Storage mod then. But I see you did make a request there too.

On a technical note, how do you expect this to work? The receptacle isn't loaded by dupes. Do you want to not unload the belt? Won't that just clog the belt then?

**Comment by TheFantasticLoki** [comment]
It could bog down the line a bit but from what Ik about how shipping works you can have a short run comming off the line to the receptacle and one that shorter run has filled items will just skip that line and move on to the next one.
