### ISSUE TITLE
Build update 544519 crashes on load with mod loaded (Spaced Out)

### ISSUE THREAD

**Issue by The-Toblin** [Truinto/ONI-Modloader-SimpleMods#40]
**Describe the bug**
If this mod is active and the U45 build is started, the game will crash on load. Watching the stack-trace indicates this mod is to blame. However, the game will not detect the mod being to blame (ie it doesn't deselect it).
[Player.log](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/10764677/Player.log)

**To Reproduce**
Install the U45 build. Install this mod. Start the game.

**[required] Debug Logs**
- attach log found here: %AppData%\..\LocalLow\Klei\Oxygen Not Included
- attach log(s) found here: Steam\SteamApps\common\OxygenNotIncluded\Mods\_Logs

**Desktop (please complete the following information):**
Arch Linux x64
Zen Kernel 6.1.11
Intel aGPU

**Comment by Truinto** [comment]
I generally don't patch beta versions. If this were a pre-release of a definitive version, I would care. But I am not putting time in a project I need to patch again a week later.

**Comment by The-Toblin** [comment]
Absolutely understandable. If nothing else, I posed this largely as a "headsup" that there might be trouble on the horizon. I don't expect you to patch a beta version.

**Comment by obuw** [comment]
The patch is now live, and the problem persists, the game crashes on load when the mod is enabled.

Seems to be something related to CompostManagerPatch.

**Comment by The-Toblin** [comment]
Reopening this as the patch is now live and this still crashes instantly on load. I haven't been able to figure out exactly why (I'm not good with logs), but it behaves identically like it did during testing.

**Comment by Truinto** [comment]
No patch needed. Just recompiled and it works.

**Comment by obuw** [comment]
Thanks for the quick fix!

**Comment by Truinto** [comment]
Sure thing
