### ISSUE TITLE
ConfigureBuildings causes ONI to crash with the latest "WhattaBlast!" update (Build U46-550759-5)

### ISSUE THREAD

**Issue by The-Toblin** [Truinto/ONI-Modloader-SimpleMods#41]
**Describe the bug**
Having "Configure Buildings" active causes ONI to crash on load with the "oops!" screen.

**To Reproduce**
1. Install ONI and SO
2. Install "Configure Buildings" mod
3. Launch
4. Crash

**[required] Debug Logs**
- attach log found here: %AppData%\..\LocalLow\Klei\Oxygen Not Included
- attach log(s) found here: Steam\SteamApps\common\OxygenNotIncluded\Mods\_Logs

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Uname -r: 6.2.8-arch-1
 - 
[Player.log](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/11119655/Player.log)

**Comment by Truinto** [comment]
Fixed afaik
