### ISSUE TITLE
Game Update 550759 Crashes When Loading a Save

### ISSUE THREAD

**Issue by jerodg** [Truinto/ONI-Modloader-SimpleMods#42]
**Describe the bug**
After the latest update (550759) you can start a new game and things will work as expected, however, loading a save game will cause a crash before the saved-game is fully loaded.

**To Reproduce**
1. Start a new game
2. Save game
3. Load saved game

**[required] Debug Logs**
[Player.log](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/11140355/Player.log)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Win11 Pro
 - v22H2 b22621.1485

**Additional context**
N/A

**Comment by Truinto** [comment]
Thank you. It's rare to get an actual bug report. Unfortunately I cannot reproduce the issue. Loading an old save or loading after creating a new colony does not cause any crashes. It also appears you are the only person who experiences this issue. I can guarantee you there are at least 3 people in the Steam comments complaining, if this were a wide spread issue.

Did you try this with a new colony or just your existing save? I can answer this from your log file. The save was _created_ with these mods active:
  - Airlock Door
  - always_request_suit_locker
  - Automation Bypass
  - Better Automation Overlay
  - Better Multitool Animations
  - Bigger Building Menu
  - Bigger Camera Zoom Out
  - build_over_plants
  - More Building Info
  - Rotate Buildings
  - schedule_master
  - Show Building Ranges
  - always_three_interests
  - bottles_to_pipes
  - Buildable Natural Tile
  - Buildable Neural Vacillator
  - Configurable Motion Sensor Range
  - Critter Proof Doors
  - sealed_critter_feeders
  - Allow Food In Storage Dispenser
  - Any Starting Dupe
  - Demolish Neutronium
  - Don't Idle in Doors
  - Double Sweeper Range
  - Duplicant Count & Stat Selector
  - Forbid Items
  - No Manual Delivery
  - Rest for the Weary
  - Stock Bug Fix
  - The Duplicant Reacharound
  - Waste Not, Want Not
  - Bigger Brushes
  - Clothing Locker
  - drywall_hides_pipes
  - egg_cryo_preservation
  - Falling Sand
  - Faster Jetpacks
  - Fervine
  - Flow Splitters
  - Full Miner Yield
  - Insulated Farm Tiles
  - Insulated Radbolt Joint Plate
  - Less Waste From Jetpacks
  - Mafic Pipes
  - Missing Element Textures
  - Movable Printing Pods
  - Move This Here
  - No Leaky Walls
  - Plastic Door
  - Rebuildable AETN
  - replace floors
  - Ribbed Fire Pole
  - Sandbox Tools
  - Set Default Deconstruct Layer
  - Squirrel Wheel
  - StoreArtifacts
  - Suit Recharger
  - Suppress Notifications
  - Sweep By Type
  - True Tiles
  - wall_pumps_and_vents
  - Better Farming Effects and Tweaks
  - Attribute-based Workshop Restrictions
  - Better Air Filter v2
  - Better Info Cards
  - Blueprints fixed
  - Clean Drop
  - Critters Can Pass
  - destructable_poi_props
  - ExtendedBridges
  - gas_overlay
  - Modern Half Door
  - Hide Panel On Build
  - insulated_door
  - insulated_joint_plate
  - Larger Gas Storage
  - Piped Output
  - Plan Buildings Without Materials
  - Popup Control
  - Priority Zero
  - rebuildable_tiles
  - Refuel Turned-Off Generators
  - Rotatable Radbolt Chamber Output
  - Rover's Recharger
  - Smart Drag Tool
  - Space POI Additional Info
  - Store Dream Journals
  - Threshold Walls
  - Unrestricted Transit Tubes
  - Customize Geyser
  - Always Show Capacity
  - Artifacts in Care Packages
  - Auto-Eject
  - Carousel
  - [Vanilla + DLC] Checkpoint Automation
  - [Vanilla + DLC] Conveyor Rail Display
  - Critter Inventory
  - Don't Starve Mr. Puft
  - Dream Journal Hitbox Fix
  - Drink Buildings Tweaked
  - Dumping Sign
  - Rest for the Weary
  - Increased Meter Limits
  - Mismatched Wire Finder
  - "Move Here" Command Tile
  - No Empty Conveyors
  - One Giant Leap
  - Partitioned Storage
  - Pipeline inspection in wall管道检测可穿墙
  - Pip Plant Overlay
  - Radioactive Wheezeworts
  - Research Queue
  - Roller Snakes Reborn
  - [Vanilla + DLC] Rooms Expanded
  - smart_mop
  - Sweep Zones
  - Where's My Loot?
  - Workshop Profiles
  - Wounded Go To Med Bed
  - Configurable Sweepy
  - Fast Save
  - Pause on ready to print
  - Stairs
  - Wrangle & Carry
  - Thermal Tooltips
  - door_icons
  - Giant Doors
  - ladder_replace
  - More Bunker Doors
  - Conveyor Loaders Are Not Machinery
  - Show Industrial Machinery Tag
  - Bio-Inks: Rechargeable Printing Pod

Maybe your save is just corrupt? If you get the same thing with saves created without any other mods, then perhaps your game files are damaged. Steam can check the integrity of your files. I am sure you find some guide for that online.

Let me know.

**Comment by jerodg** [comment]
Well, it was weird because I started a new game and it worked until I quit and attempted to load again. I ended up wiping my PC of all things ONI and reinstalling; No longer experiencing the crash.

```text
  (°_o)
¯\(   )/¯
  /   \
```
