### ISSUE TITLE
[CustomizeBuildings] Thermo Aquacooler crash

### ISSUE THREAD

**Issue by ezonius** [Truinto/ONI-Modloader-SimpleMods#55]
**Describe the bug**
Crash on running a Aquacooler with AbsoluteOutput on. 
The temperature/kjoules slider overlay is not working for Aquacooler.
When AbsoluteOutput is off, the aquacooler can only take 10kg/s even when pipes are set to more (100kg/s in my case).

**To Reproduce**
Have: "AirConditionerAbsoluteOutput": true
Pipe liquid into to running Aquatuner (i used Polluted Water)
Crash

**[required] Debug Logs**
[Player-prev.log](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/13796965/Player-prev.log)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 
 - Version: 22H2 22621.2715

**Comment by Truinto** [comment]
Something wrong here. The log says it crashed on boot up. Which should prevent you from getting into the game. Do you have development enabled?

**Comment by ezonius** [comment]
Made a new log with same procedure just to be sure.

I let the game run for a few seconds, with the pipe disconnected. Paused the game. Reconnected the pipe with liquid, (Polluted Water 100kg/s) let the liquid flow, and then it crashes the second the liquid goes from the last pipe, to the aquacooler.

[Player.log](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/13806608/Player.log)

I'm not using development mode.

**Comment by ezonius** [comment]
I've messed up.
I don't know why I thought that the Thermo AquaCOOLER was a part of this mod, but I did and that's why I made the issue here. It's part the the "HVAC Expansion" mod. Sorry for the inconvenience.
