### ISSUE TITLE
[PipedEverything] causes "Unable to Resolve: Cobaltite in MetalRefinery

### ISSUE THREAD

**Issue by mpeele1** [Truinto/ONI-Modloader-SimpleMods#59]
**Describe the bug**
The mod seems to work, but gives me this popup dialog message. 
[Player-prev.log](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/14413650/Player-prev.log)

**To Reproduce**
Have mod enabled. Load game. I'm not sure if other mods conflict... 

**[required] Debug Logs**
- attach log found here: %AppData%\..\LocalLow\Klei\Oxygen Not Included
- attach log(s) found here: Steam\SteamApps\common\OxygenNotIncluded\Mods\_Logs
    - Not found

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Additional context**

**Comment by Truinto** [comment]
Your game does not have these elements, so they are skipped. This will work fine. If you dislike the message, you can enable the DLC or remove the elements from the configuration.

**Comment by mpeele1** [comment]
Thanks.
