### ISSUE TITLE
Adjustable Transformers?

### ISSUE THREAD

**Issue by TroublesomeCorvid** [Truinto/ONI-Modloader-SimpleMods#6]
So, the ability to customize the wattage capacity on wires is great and all....

.... But that means diddly squat if you can't adjust the output on your transformers to match.

I've looked at [CynicalBusiness's Adjustable Transformers](https://steamcommunity.com/sharedfiles/filedetails/?id=1885249412), but all that does is let you lower the wattage from the maximum level.  (Although it does set the maximum wattage for the Large Power Transformer from 4 kilowatts to 20 kilowatts.)

Is there a way to do this in the settings file that I've somehow missed, or is this a legit missing feature?

**Comment by Truinto** [comment]
This simply requires one additional BuildingDef field. I will add this eventually. It probably is already doable with AdvancedSettings, but I havn't documented that, because it's too complicated to use (an the code is somewhat messy/ugly/unreliable).

**Comment by Truinto** [comment]
Added the requested field. I didn't test it yet, but with 90% certainty this should work:
`  "BuildingBaseSettings": {
    "PowerTransformer": {
      "GeneratorWattageRating": 8000.0,
      "GeneratorBaseCapacity": 8000.0
    }`
