### ISSUE TITLE
[Customize Buildings] update for localization data

### ISSUE THREAD

**Issue by neavo** [Truinto/ONI-Modloader-SimpleMods#63]
I think the Chinese localization data that comes with the mod needs to be updated, the translation of some of the terms is really hard to understand and doesn't match the readme.
But unfortunately I found out that the mod uses the localization string as the key of the config file, once a change is made to the localization terms, the player will lose his mod settings ...
If this problem can be solved, I can maintain and update the Chinese localization data，include Customize Buildings and other mods.

**Comment by neavo** [comment]
In my development experience, it's not a good idea to mix data configuration with description text, it's better to keep it separate, the configuration file just needs the original key in English

**Comment by Truinto** [comment]
I will remove the "PROPERTY" key in future releases. If these are missing, then the config won't be translated. I will also remove individual config files per language.
[strings_NEW.txt](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/15080911/strings_NEW.txt)

(Here is a regex, if useful `#.*\.PROPERTY\..*\n.*\n.*\n.*\n.*\n` check that format line end is set to UNIX.)

**Comment by neavo** [comment]
> I will remove the "PROPERTY" key in future releases. If these are missing, then the config won't be translated. I will also remove individual config files per language. [strings_NEW.txt](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/15080911/strings_NEW.txt)
> 
> (Here is a regex, if useful `#.*\.PROPERTY\..*\n.*\n.*\n.*\n.*\n` check that format line end is set to UNIX.)

should I use this .txt file or the .po file in the mod to translate?

**Comment by Truinto** [comment]
It's the same, minus the property entries. Github doesn't allow .po extension.

**Comment by Truinto** [comment]
I will assume you went on. If anyone wants to submit a translation, just let me know.
