### ISSUE TITLE
Customize Buildings,  Max setting for Liquid Reservoir is not limiting.

### ISSUE THREAD

**Issue by Jase2z** [Truinto/ONI-Modloader-SimpleMods#64]
**Describe the bug**
With Customize Buildings mod the max setting for limiting Liquid Reservoir size is not limiting its size. It continues to add liquid beyond the max setting.

**To Reproduce**
1. Add liquid to a reservoir.
2. Set the reservoirs max setting.
3. Wait until the liquid weight exceeds max.
4. Watch how max isn't limiting.

**[required] Debug Logs**
I have no debug logs as far as I know.

**Screenshots**
I have no screenshots.

**Desktop (please complete the following information):**
 - OS: Windows 11, Steam
 - ONI version on Steam: 13861223
 - Customize Buildings: v1.0.91.14

**Additional context**
I did an unsubscribe and resubscribe to see if reinstalling would help, and it didn't.

**Comment by Truinto** [comment]
The feature you are describing is attaching the storage locker function to the reservoirs. All related controls work exactly as vanilla. In practice, this means only Duplicants respect them. If you route the wrong element or too much material into the storage via pipes, then the storage locker part will not prevent that.

So it's not a bug and I from my point of view working as intended. The labels are just not very informative. I also have this problem with other 'borrowed' controls.

**Comment by Jase2z** [comment]
Thank you for the prompt reply. I understand now how the Max weight setting for the Liquid Reservior only applies to Duplicants. I was using pipes.
