### ISSUE TITLE
[Customize Recipe] Trouble with recipe id

### ISSUE THREAD

**Issue by GNR2012** [Truinto/ONI-Modloader-SimpleMods#68]
My config is unable to work properly with recipes coming from buildings that has underscore name. The particular recipes and buildings are coming from a mod called Chemical Processing: Industrial Overhaul Edition (https://steamcommunity.com/sharedfiles/filedetails/?id=2661907148).

For example with this recipe in the config:

{
      "Id": "Chemical_AdvancedMetalRefinery_I_Cuprite_RefinedCarbon_Sand_O_Copper_SolidSlag",
      "Building": "Chemical_AdvancedMetalRefinery",
      "Inputs": [
        {
          "material": "Cuprite",
          "amount": 400.0
        },
        {
          "material": "RefinedCarbon",
          "amount": 50.0
        },
        {
          "material": "Sand",
          "amount": 50.0
        }
      ],
      "Outputs": [
        {
          "material": "Copper",
          "amount": 400.0
        },
        {
          "material": "SolidSlag",
          "amount": 100.0
        }
      ],
      "Time": 40.0,
      "HEP": 0,
      "HEPout": 0,
      "Description": "Smelt a mixture of <link=\"CUPRITE\">Copper Ore</link>, <link=\"CARBON\">Coal</link> and <link=\"SAND\">Sand</link>, to produce <link=\"COPPER\">Copper</link>. Produce <link=\"SOLIDSLAG\">Slag</link>, as waste."
    }

There will be warning in the start menu that the recipe is invalid and any recipe modification won't be applied in-game. Even if I remove the id in the config file, the warning is still there and the recipe modification still won't applied.

![CustomizeRecipe Problem](https://github.com/user-attachments/assets/f0c371e5-fd4b-45e6-9aaa-87a504cd0f88)

**Comment by kaedys** [comment]
Looks like it is assuming the building name lacks underscores, and [that the first underscore](https://github.com/Truinto/ONI-Modloader-SimpleMods/blob/master/src/CustomizeRecipe/RecipePatch.cs#L101) separates the building ID from the rest of the recipe name.  What it should probably do is check that the `Building` field maps to a proper prefab, and that the `Id` field starts with the `Building` field substring.

**Comment by Truinto** [comment]
Good point
