### ISSUE TITLE
Custom Plants doesn't work correctly on Arbor Tree

### ISSUE THREAD

**Issue by AisonSu** [Truinto/ONI-Modloader-SimpleMods#7]
`      "id": "ForestTree",
       "fruitId":"WoodLog",
      "irrigation": {
      },
      "output_element":"Oxygen",
      "output_rate":0.0325
    }`
This will cause the game a error when it drop automatically，with the arbor tree should not have harvesting cycle.That is what branch should do.And it seems cause the amount is uncorrected,when i try to use ForestTreeSeed,and some time it also happenend when it is WoodLog (i am not sure which one,but it happens actually)

**Comment by Truinto** [comment]
Sorry, didn't read earlier.
So, arbor trees are really unique and weird. For my mod, I handle all of these entities the same, which doesn't work well with the previous statement. To elaborate, the trunk is a plant and it has most of the same properties as other plants, but some work differently, like the fruits which it doesn't have. Instead there is a separate plant, branches, which are a game component that are spawned by the trunk. These mostly work like one would expect and can grow fruits.

So, for your example, just remove the fruitId. I think...
