### ISSUE TITLE
[PipedEverything] Feature Request: Ice Liquefier Default

### ISSUE THREAD

**Issue by Nealkitt** [Truinto/ONI-Modloader-SimpleMods#70]
**Is your feature request related to a problem? Please describe.**
New DLC Ice Liquefier Pipes for PipedEverything

**Describe the solution you'd like**
Default for the Ice Liquefier, for the new DLC content with this mod

**Describe alternatives you've considered**
I found out the default I made after painstakingly finding the right ID because I am dumb, is very beneficial and on par with the scope of this mod., so you can pipe it into liquid reservoirs
     {
      "Id": "IceKettle",
      "Input": false,
      "OffsetX": 0,
      "OffsetY": 0,
      "Filter":[
        "Water"
      ],
      "StorageIndex": 2
    },

**Additional context**
I'm too lazy to make a PR, that might get adjusted, and I work in Kotlin more than other formats
![image](https://github.com/user-attachments/assets/41673186-fafc-4e1c-b1e2-6bfa5d6c3d99)
If you want you can close this issue rather quickly if it wouldn't make sense, I just found it would be beneficial for people playing on the new DLC

**Comment by Nealkitt** [comment]
Renamed it to be alongside the other issues and feature requests

**Comment by Truinto** [comment]
Done. I made some improvements. Delete your config, to update it.

Btw, you can just use the ingame name inplace of ids.
