### ISSUE TITLE
Customize Buildings Localization

### ISSUE THREAD

**Issue by DarkEviL88** [Truinto/ONI-Modloader-SimpleMods#74]
Translating these strings doesn't work for me:

#. CustomizeBuildings.LOCSTRINGS.SpaceHeaterSliderLogic
msgctxt "CustomizeBuildings.LOCSTRINGS.SpaceHeaterSliderLogic"
msgid "Operates until temperature reached:\n(Above/below does nothing)"
msgstr "Работает до достижения температуры:\n(Игрорируйте кнопки Выше/Ниже)"

#. CustomizeBuildings.LOCSTRINGS.AdvancedConditionerModLogic
msgctxt "CustomizeBuildings.LOCSTRINGS.AdvancedConditionerModLogic"
msgid "Output exactly this temperature:\n(MIN temperature does -14°C instead)"
msgstr "Выводить указанную температуру:\n(Вместо мин. температуры -14°C)"

![image](https://github.com/user-attachments/assets/73389350-15dd-465b-83fe-1076a968e4d1)
![image](https://github.com/user-attachments/assets/44e2f9ee-1621-43bb-b99f-81c1e257cb16)
![image](https://github.com/user-attachments/assets/9ceb0634-25e2-4654-85dd-b7366f152223)
![image](https://github.com/user-attachments/assets/758312ab-1c57-4048-a50f-d1eeb3319a00)

The translation of the other strings works fine.
Since this issue is not very important, I have not opened a bug or feature request, if you have the opportunity or free time, please check if everything is ok, maybe I made a mistake. Thank you.

**Comment by Truinto** [comment]
> I have not opened a bug or feature request
But this is a bug report...

Anyway, I have fixed the issue with v1.102

**Comment by DarkEviL88** [comment]
Thx
